// ─── Dummy Data ────────────────────────────────────────────────────────────────
// Shared across DepartmentPage, SubjectPage, CoursePage, LecturePage
// Replace with real API calls in Phase 2.

export const departments = [
  {
    id: "cs",
    name: "Computer Science",
    shortName: "CS",
    description: "Algorithms, systems, AI, web & software engineering.",
    icon: "💻",
    color: "from-violet-600 to-indigo-600",
    bgLight: "bg-violet-50",
    border: "border-violet-200",
    badge: "text-violet-700 bg-violet-100",
    totalCourses: 24,
    totalStudents: 1840,
    subjects: ["dsa", "os", "cn", "dbms", "ai", "webdev"],
  },
  {
    id: "mech",
    name: "Mechanical Engineering",
    shortName: "ME",
    description: "Thermodynamics, fluid mechanics, design & manufacturing.",
    icon: "⚙️",
    color: "from-orange-500 to-amber-500",
    bgLight: "bg-orange-50",
    border: "border-orange-200",
    badge: "text-orange-700 bg-orange-100",
    totalCourses: 18,
    totalStudents: 1120,
    subjects: ["thermo", "fluid", "som", "manufacturing"],
  },
  {
    id: "elex",
    name: "Electronics & Comm.",
    shortName: "EC",
    description: "Circuits, signals, embedded systems & communications.",
    icon: "🔌",
    color: "from-cyan-600 to-teal-500",
    bgLight: "bg-cyan-50",
    border: "border-cyan-200",
    badge: "text-cyan-700 bg-cyan-100",
    totalCourses: 20,
    totalStudents: 1350,
    subjects: ["analog", "digital", "signals", "embedded"],
  },
  {
    id: "civil",
    name: "Civil Engineering",
    shortName: "CE",
    description: "Structures, geotechnics, transportation & environment.",
    icon: "🏗️",
    color: "from-emerald-600 to-green-500",
    bgLight: "bg-emerald-50",
    border: "border-emerald-200",
    badge: "text-emerald-700 bg-emerald-100",
    totalCourses: 15,
    totalStudents: 890,
    subjects: ["structures", "geo", "transport"],
  },
  {
    id: "chem",
    name: "Chemical Engineering",
    shortName: "CH",
    description: "Process design, reaction engineering & thermodynamics.",
    icon: "🧪",
    color: "from-pink-600 to-rose-500",
    bgLight: "bg-pink-50",
    border: "border-pink-200",
    badge: "text-pink-700 bg-pink-100",
    totalCourses: 12,
    totalStudents: 670,
    subjects: ["process", "reaction", "masstransfer"],
  },
  {
    id: "math",
    name: "Mathematics",
    shortName: "MTH",
    description: "Calculus, linear algebra, probability & discrete math.",
    icon: "📐",
    color: "from-blue-600 to-sky-500",
    bgLight: "bg-blue-50",
    border: "border-blue-200",
    badge: "text-blue-700 bg-blue-100",
    totalCourses: 10,
    totalStudents: 2100,
    subjects: ["calculus", "linalg", "prob", "discrete"],
  },
];

export const subjects = {
  // CS
  dsa: {
    id: "dsa",
    deptId: "cs",
    name: "Data Structures & Algorithms",
    description:
      "Master arrays, linked lists, trees, graphs, dynamic programming and competitive coding.",
    instructor: "Prof. Ramesh Gupta",
    thumbnail: "https://placehold.co/400x220/6d28d9/ffffff?text=DSA",
    totalCourses: 4,
    totalLectures: 62,
    level: "Intermediate",
  },
  os: {
    id: "os",
    deptId: "cs",
    name: "Operating Systems",
    description:
      "Processes, scheduling, memory management, file systems and concurrency.",
    instructor: "Prof. Sunita Rao",
    thumbnail: "https://placehold.co/400x220/4338ca/ffffff?text=OS",
    totalCourses: 3,
    totalLectures: 48,
    level: "Advanced",
  },
  cn: {
    id: "cn",
    deptId: "cs",
    name: "Computer Networks",
    description:
      "OSI model, TCP/IP, routing, DNS, HTTP, and network security fundamentals.",
    instructor: "Prof. Ajay Mehta",
    thumbnail: "https://placehold.co/400x220/0e7490/ffffff?text=CN",
    totalCourses: 3,
    totalLectures: 44,
    level: "Intermediate",
  },
  dbms: {
    id: "dbms",
    deptId: "cs",
    name: "Database Management Systems",
    description:
      "ER models, SQL, normalization, transactions, indexing and NoSQL.",
    instructor: "Prof. Priya Nair",
    thumbnail: "https://placehold.co/400x220/065f46/ffffff?text=DBMS",
    totalCourses: 3,
    totalLectures: 38,
    level: "Beginner",
  },
  ai: {
    id: "ai",
    deptId: "cs",
    name: "Artificial Intelligence",
    description:
      "Search, knowledge representation, ML basics, neural networks and NLP intro.",
    instructor: "Prof. Kiran Bhat",
    thumbnail: "https://placehold.co/400x220/7c3aed/ffffff?text=AI",
    totalCourses: 5,
    totalLectures: 70,
    level: "Advanced",
  },
  webdev: {
    id: "webdev",
    deptId: "cs",
    name: "Web Development",
    description:
      "HTML, CSS, JavaScript, React, Node.js and full-stack project building.",
    instructor: "Prof. Divya Sharma",
    thumbnail: "https://placehold.co/400x220/b45309/ffffff?text=Web+Dev",
    totalCourses: 6,
    totalLectures: 85,
    level: "Beginner",
  },
  // MECH
  thermo: {
    id: "thermo",
    deptId: "mech",
    name: "Thermodynamics",
    description: "Laws of thermodynamics, cycles, entropy and heat engines.",
    instructor: "Prof. Anil Verma",
    thumbnail: "https://placehold.co/400x220/c2410c/ffffff?text=Thermo",
    totalCourses: 3,
    totalLectures: 40,
    level: "Intermediate",
  },
  fluid: {
    id: "fluid",
    deptId: "mech",
    name: "Fluid Mechanics",
    description: "Fluid statics, Bernoulli, viscous flow and turbomachinery.",
    instructor: "Prof. Meera Singh",
    thumbnail: "https://placehold.co/400x220/0369a1/ffffff?text=Fluids",
    totalCourses: 2,
    totalLectures: 32,
    level: "Intermediate",
  },
  // EC
  analog: {
    id: "analog",
    deptId: "elex",
    name: "Analog Circuits",
    description: "Op-amps, amplifiers, filters and analog signal processing.",
    instructor: "Prof. Suresh Kumar",
    thumbnail: "https://placehold.co/400x220/0f766e/ffffff?text=Analog",
    totalCourses: 3,
    totalLectures: 42,
    level: "Intermediate",
  },
  digital: {
    id: "digital",
    deptId: "elex",
    name: "Digital Electronics",
    description: "Logic gates, flip-flops, counters, FSMs and VHDL basics.",
    instructor: "Prof. Rekha Pillai",
    thumbnail: "https://placehold.co/400x220/1d4ed8/ffffff?text=Digital",
    totalCourses: 4,
    totalLectures: 55,
    level: "Beginner",
  },
};

export const courses = {
  dsa: [
    {
      id: "dsa-c1",
      subjectId: "dsa",
      title: "Arrays & Strings Masterclass",
      description: "Sliding window, two pointers, prefix sums and interview patterns.",
      instructor: "Prof. Ramesh Gupta",
      thumbnail: "https://placehold.co/400x220/6d28d9/ffffff?text=Arrays",
      duration: "6h 20m",
      lectureCount: 18,
      level: "Beginner",
      rating: 4.8,
      enrolled: 520,
    },
    {
      id: "dsa-c2",
      subjectId: "dsa",
      title: "Linked Lists, Stacks & Queues",
      description: "Build every variant from scratch and solve real problems.",
      instructor: "Prof. Ramesh Gupta",
      thumbnail: "https://placehold.co/400x220/4c1d95/ffffff?text=LL+SQ",
      duration: "5h 45m",
      lectureCount: 14,
      level: "Beginner",
      rating: 4.7,
      enrolled: 410,
    },
    {
      id: "dsa-c3",
      subjectId: "dsa",
      title: "Trees & Graphs",
      description: "BST, heaps, BFS, DFS, shortest paths and spanning trees.",
      instructor: "Prof. Ramesh Gupta",
      thumbnail: "https://placehold.co/400x220/5b21b6/ffffff?text=Trees",
      duration: "8h 10m",
      lectureCount: 22,
      level: "Intermediate",
      rating: 4.9,
      enrolled: 380,
    },
    {
      id: "dsa-c4",
      subjectId: "dsa",
      title: "Dynamic Programming",
      description: "Memoization, tabulation, classic DP patterns and advanced problems.",
      instructor: "Prof. Ramesh Gupta",
      thumbnail: "https://placehold.co/400x220/3730a3/ffffff?text=DP",
      duration: "7h 30m",
      lectureCount: 20,
      level: "Advanced",
      rating: 4.9,
      enrolled: 290,
    },
  ],
  os: [
    {
      id: "os-c1",
      subjectId: "os",
      title: "Process Management & Scheduling",
      description: "Process states, context switching, CPU scheduling algorithms.",
      instructor: "Prof. Sunita Rao",
      thumbnail: "https://placehold.co/400x220/4338ca/ffffff?text=Processes",
      duration: "5h 00m",
      lectureCount: 15,
      level: "Intermediate",
      rating: 4.6,
      enrolled: 310,
    },
    {
      id: "os-c2",
      subjectId: "os",
      title: "Memory Management",
      description: "Paging, segmentation, virtual memory and page replacement.",
      instructor: "Prof. Sunita Rao",
      thumbnail: "https://placehold.co/400x220/3730a3/ffffff?text=Memory",
      duration: "4h 30m",
      lectureCount: 13,
      level: "Advanced",
      rating: 4.7,
      enrolled: 240,
    },
  ],
  webdev: [
    {
      id: "web-c1",
      subjectId: "webdev",
      title: "HTML & CSS Fundamentals",
      description: "Semantic HTML, Flexbox, Grid and responsive design.",
      instructor: "Prof. Divya Sharma",
      thumbnail: "https://placehold.co/400x220/b45309/ffffff?text=HTML+CSS",
      duration: "4h 00m",
      lectureCount: 12,
      level: "Beginner",
      rating: 4.8,
      enrolled: 760,
    },
    {
      id: "web-c2",
      subjectId: "webdev",
      title: "JavaScript: Zero to ES2024",
      description: "Variables, closures, async/await, modules and DOM manipulation.",
      instructor: "Prof. Divya Sharma",
      thumbnail: "https://placehold.co/400x220/92400e/ffffff?text=JS",
      duration: "9h 15m",
      lectureCount: 28,
      level: "Beginner",
      rating: 4.9,
      enrolled: 840,
    },
    {
      id: "web-c3",
      subjectId: "webdev",
      title: "React JS",
      description: "Components, hooks, context, Redux and building real projects.",
      instructor: "Prof. Divya Sharma",
      thumbnail: "https://placehold.co/400x220/78350f/ffffff?text=React",
      duration: "11h 00m",
      lectureCount: 32,
      level: "Intermediate",
      rating: 4.9,
      enrolled: 620,
    },
  ],
};

export const lectures = {
  "dsa-c1": [
    { id: "l1", courseId: "dsa-c1", title: "Introduction to Arrays", duration: "18:24", isPreview: true, isCompleted: false },
    { id: "l2", courseId: "dsa-c1", title: "Array Traversal & Basic Operations", duration: "22:10", isPreview: false, isCompleted: false },
    { id: "l3", courseId: "dsa-c1", title: "Two Pointer Technique", duration: "28:45", isPreview: false, isCompleted: false },
    { id: "l4", courseId: "dsa-c1", title: "Sliding Window — Fixed Size", duration: "24:30", isPreview: false, isCompleted: false },
    { id: "l5", courseId: "dsa-c1", title: "Sliding Window — Variable Size", duration: "30:15", isPreview: false, isCompleted: false },
    { id: "l6", courseId: "dsa-c1", title: "Prefix Sums", duration: "20:00", isPreview: true, isCompleted: false },
    { id: "l7", courseId: "dsa-c1", title: "Kadane's Algorithm", duration: "19:50", isPreview: false, isCompleted: false },
    { id: "l8", courseId: "dsa-c1", title: "String Basics & Character Arrays", duration: "17:35", isPreview: false, isCompleted: false },
    { id: "l9", courseId: "dsa-c1", title: "Anagram & Palindrome Problems", duration: "25:00", isPreview: false, isCompleted: false },
    { id: "l10", courseId: "dsa-c1", title: "Matrix Traversal", duration: "23:10", isPreview: false, isCompleted: false },
    { id: "l11", courseId: "dsa-c1", title: "Rotate & Spiral Matrix", duration: "27:40", isPreview: false, isCompleted: false },
    { id: "l12", courseId: "dsa-c1", title: "Binary Search on Arrays", duration: "29:05", isPreview: false, isCompleted: false },
    { id: "l13", courseId: "dsa-c1", title: "Sorting Algorithms", duration: "35:00", isPreview: false, isCompleted: false },
    { id: "l14", courseId: "dsa-c1", title: "Dutch National Flag Problem", duration: "18:20", isPreview: false, isCompleted: false },
    { id: "l15", courseId: "dsa-c1", title: "Interview Practice — Easy Sets", duration: "40:00", isPreview: false, isCompleted: false },
    { id: "l16", courseId: "dsa-c1", title: "Interview Practice — Medium Sets", duration: "45:30", isPreview: false, isCompleted: false },
    { id: "l17", courseId: "dsa-c1", title: "Interview Practice — Hard Sets", duration: "50:00", isPreview: false, isCompleted: false },
    { id: "l18", courseId: "dsa-c1", title: "Wrap-up & Cheat Sheet", duration: "10:00", isPreview: true, isCompleted: false },
  ],
  "dsa-c2": [
    { id: "l1", courseId: "dsa-c2", title: "Singly Linked List", duration: "20:00", isPreview: true, isCompleted: false },
    { id: "l2", courseId: "dsa-c2", title: "Doubly & Circular Linked Lists", duration: "22:30", isPreview: false, isCompleted: false },
    { id: "l3", courseId: "dsa-c2", title: "Reverse & Detect Cycle", duration: "25:00", isPreview: false, isCompleted: false },
    { id: "l4", courseId: "dsa-c2", title: "Stack — Implementation", duration: "18:00", isPreview: false, isCompleted: false },
    { id: "l5", courseId: "dsa-c2", title: "Stack — Applications (parentheses, NGE)", duration: "28:00", isPreview: false, isCompleted: false },
    { id: "l6", courseId: "dsa-c2", title: "Queue & Deque", duration: "20:00", isPreview: false, isCompleted: false },
    { id: "l7", courseId: "dsa-c2", title: "Priority Queue & Heap Intro", duration: "24:00", isPreview: false, isCompleted: false },
  ],
};

// Helper to get dept by id
export const getDept = (id) => departments.find((d) => d.id === id);

// Helper to get subjects for a dept
export const getSubjectsForDept = (deptId) =>
  Object.values(subjects).filter((s) => s.deptId === deptId);

// Helper to get courses for a subject
export const getCoursesForSubject = (subjectId) => courses[subjectId] || [];

// Helper to get lectures for a course
export const getLecturesForCourse = (courseId) => lectures[courseId] || [];
